### ISSUE TITLE
[proposal] [maintainers] simple GitHub issue template

### ISSUE THREAD

**Issue by efx** [exercism/rust#1237]
I like how GitHub issue templates can help triage issues at creation time.

I recently contributed to nushell and like their 2 basic [templates](https://github.com/nushell/nushell/tree/a148c640b29db3580b783f3dce830dd19f68c3ae/.github/ISSUE_TEMPLATE):
- bug
- feature / feedback?

In my opinion the v3 monorepo issue creation presented too many options.

So:
1. Should we introduce templates for issues?
2. What should they be?

GitHub has PR templates but I feel that would be too complex for our current needs.

**Comment by coriolinus** [comment]
I'm not opposed in principle, but I can say that in my experience, issue and PR templates aren't actually that useful. People unfamiliar with open source codebases ignore them because they feel like reading the docs. Frequent contributors to the project ignore them because they're just chaff. The sweet spot where they provide value seems very narrow.

Still, we could give try.

**Comment by efx** [comment]
That experience is quite helpful!

> Frequent contributors to the project ignore them because they're just chaff.

Good point. Given those contributing to this know what they are doing, it seems preemptive to introduce templates.

I'm happy with saying "we have considered this but not now". 

Should we find a number of new contributors that could benefit from this branching, or others with stronger opinions on the matter, we can reopen.
