### ISSUE TITLE
Two-Fer starts with a file that already satisfies all tests

### ISSUE THREAD

**Issue by wischi-chr** [exercism/rust#1266]
I'm not sure if this is a problem with the exercise, v3 or even not a bug at all.

https://exercism.lol/tracks/rust/exercises/two-fer/edit
https://github.com/exercism/rust/tree/main/exercises/practice/two-fer

After starting the exercise there is basically nothing left to do besides pressing F2 ("run tests")

**Comment by coriolinus** [comment]
Two-fer is deprecated and should not be visible in the v3 website:

https://github.com/exercism/rust/blob/519032f2a56902b552d9524fcc6285b21a8b858e/config.json#L1419-L1431

There was a problem, years ago, which broke things if we removed it entirely, so deprecation was the best we could do.

**Comment by ErikSchierboom** [comment]
I think it will be visible to students that started the exercise when it was still not deprecated, right @iHiD?

**Comment by iHiD** [comment]
It will. That's not really a problem in itself as the nature of having starting it means they'll probably have a solution. However, because we have the "reset exercise" functionality in v3, where a student can go back to the start of an exercise if they get stuck, this does become important.

@coriolinus Is there an old stub we can revert to? Or if not, we should probably just make this stub an empty file.

**Comment by coriolinus** [comment]
Previous discussion: https://github.com/exercism/rust/pull/832. 

I note that the exercise has been deprecated for over two years. It seems unlikely to me that any student has opened but not completed that exercise in that span.

See also: https://github.com/exercism/rust/pull/773#issuecomment-490643904, https://github.com/exercism/rust/issues/564, https://github.com/exercism/rust/issues/547, https://github.com/exercism/rust/issues/552.

**Comment by iHiD** [comment]
As there are 22 people in that group, I've opened https://github.com/exercism/rust/pull/1267
