### ISSUE TITLE
Unusual waiting time for resubmitted sublist exercise 

### ISSUE THREAD

**Issue by paul-schaaf** [exercism/rust#1278]
In the rust course, in the core track, Ive been waiting for 46 days to have my sublist exercise corrected. This seems somewhat unusual. For most of my exercises I had never had to wait for more than a week. Obv the estimate of 6 hours given in the exercise is just a median, but a waiting time of 46 days was too unusual for me not to at least create an issue. Maybe there's a bug somewhere? Notably, this was my only exercise so far which was put back into the mentor queue.

**Comment by coriolinus** [comment]
The rust track has a severe deficit of mentors, which is a known issue. In any case it appears that someone has since mentored your solution, as the only sublist implemention currently requiring mentoring was submitted 7 minutes ago.

I'm going to close this issue; the balance of probability seems to me less that there is an exercism bug, and more that it just took an unusually long time to get to your solution. Sorry about that.
