### ISSUE TITLE
Macros exercise

### ISSUE THREAD

**Issue by gwendalF** [exercism/rust#1343]
Hello,

For the macros exercies for making an hashmap! macro I have trouble understand the test `test_type_override()`. The comment explains to use the std::collections::HashMap module (which I understand, our macros is bluid for that) but the test seems to failed if I use this and pass if I use `::std::collections::HashMap`. Either I misanderstand which module `::std::collections` refer  or the test pass with the wrong intent. I think it should pass if we use `std::collections::HashMap` and failed otherwise. Am I correct or do I confuse the module used?

**Comment by coriolinus** [comment]
`std::collections::HashMap` and `::std::collections::HashMap` are _usually_ two different ways of referring to the same item. However, it's entirely possible that someone brings a different `HashMap` into scope, or otherwise overrides a path somewhere such that unaltered access to a `HashMap` fails. Your macro should work even in that circumstance, which is what `test_type_override` tests.

So what does the leading `::` signify? It's a [path qualifier indicating that we want a global path](https://doc.rust-lang.org/reference/paths.html#path-qualifiers). In other words, it means that even if the item located at `std::collections::Hashmap` has been redefined, we actually want the version from the standard library. 

In the end, this is not a bug; the test is operating as intended.
