### ISSUE TITLE
Should there be a placeholder src/lib.rs for all exercises?

### ISSUE THREAD

**Issue by mkantor** [exercism/rust#269]
I noticed that several of the exercises have placeholder implementations with various levels of verbosity (e.g. [all-your-base](https://github.com/exercism/xrust/blob/master/exercises/all-your-base/src/lib.rs), [grains](https://github.com/exercism/xrust/blob/master/exercises/grains/src/lib.rs), [react](https://github.com/exercism/xrust/blob/master/exercises/react/src/lib.rs), [space-age](https://github.com/exercism/xrust/blob/master/exercises/space-age/src/lib.rs)). However this is absent from most of the exercises. I was unable to find documentation to suggest whether these files should or should not exist.

Anyway, it could probably be considered a bug one way or the other. I'm willing to help standardize things.

**Comment by petertseng** [comment]
What I see in #117 and #200: I'm not sure what to make of discussions on what they should contain, but everyone seemed to agree that a lib/src.rs should at least exist, even if it is empty.

> documentation

Our track's README is anemic and does not contain most of the starter content in https://github.com/exercism/request-new-language-track/blob/master/README.md , as it seems it was based off of https://github.com/exercism/request-new-language-track/blob/53b185fdc67f0e5e7bc2b0891c2a1cb30e4b5f05/README.md instead. Even though not every single piece of starter content needs to be included, I recommend at least a review of each item in that starter README to evaluate whether it should be included.

**Comment by mkantor** [comment]
@petertseng thanks, I neglected to search closed issues but I see there's a lot of good discussion already there. After reading everyone's arguments I'm on the fence about providing stub signatures, but agree that at the very least empty src/lib.rs files in every exercise would be nice. I'll send a PR to that effect in the near future.

**Comment by IanWhitney** [comment]
Here's my thoughts.

When we decide if there should be stub files we should think about who our students are. 

If our student is someone new to Rust, then I think there is a lot of value in having them write the entire function themselves, including the signature.  Not every exercise will have a interesting signature to write, but enough of them do. And thinking about "I want to accept type `x` and return type `y`" is the core of writing Rust (or at least it is for me, your mileage may vary).

If our student is someone familiar with Rust but trying to write better-designed implementations, then having the method signature makes more sense. They already understand that part of Rust and want to work on 'cleaner' code.

Personally, I'm a Rust learner, so I favor the first approach.

**Comment by jcdyer** [comment]
> The second approach is basically reading the signature

Learning how to read a compiler error, and get from there to a method signature is a valuable skill for new rust developers to learn.  Even if you're just appeasing the compiler, it's good to learn that this function needs to be marked pub, and that reference needs to be mutable in order to do a particular thing with it.

The problem, as I mentioned in #275 (now closed in favor of this ticket) is that the compiler errors from the tests make you fix all the issues before you can even get started.  One solution is to provide stub functions that eliminate those issues.  Another is to fully comment out all the tests but the first one, instead of marking them with `#[ignore]`, so the learner can address them one at a time, and get the experience of building up an app from scratch, one feature at a time.

**Comment by petertseng** [comment]
> the compiler errors from the tests make you fix all the issues before you can even get started

I'm obligated to ensure that [previously mentioned proposals](https://github.com/exercism/xrust/issues/200#issuecomment-246202425) get mentioned - consider using https://doc.rust-lang.org/book/conditional-compilation.html for it.

**Comment by IanWhitney** [comment]
I experimented with conditional compilation a bit. I found it to be a clunky solution to the problem. But it's likely that I was doing it wrong.

**Comment by ijanos** [comment]
I think commenting out code is simple and easy to understood even for beginners. 

I still prefer the stub file approach though :)

**Comment by petertseng** [comment]
I was thinking it'd be easier for https://github.com/exercism/xrust/blob/master/_test/check-exercises.sh#L44 to work with `#[cfg(feature = "remove this line when you're ready to test")]` than to uncomment. But we can make it easier if the comment start/end were specific strings like `/* move this line below the next test when you are ready for it` and either something like `exercism */` or (this will bite often since we will often get it wrong, I'm sure) make sure the `*/` is the last line in the file.

I personally don't think I gain a lot out of reconstructing the stubs from the tests, so I can say I would prefer to have the signatures in the stub files. This is based on the fact that starting with a test and no code is not reflective of how I code normally at all - if I were coding from scratch I would have decided the function signature before writing the test. The fact that the test is already determined means I have relatively little choice in the signature.

However, I also don't care enough to go and populate the stub files with signatures myself!

It occurs to me that if we provide signatures, it's relatively easy for a student who does not want them to simple `truncate -s0 src/lib.rs`, but harder to do it the other way around (student copies signatures from example solution?).

Whichever we choose, we'll obviously fail to make someone happy. In the far future we could allow the student to configure whether the stub files should have signatures or be empty as in https://github.com/exercism/discussions/issues/114#issuecomment-291341874, but we can't wait for that to make a decision since it is the far future.

I wonder if it'd be smart to survey students working through the Rust track and see what they think, in a similar fashion as https://gist.github.com/behrtam/9b1aaae227b5e67dd145ecd5f74e58eb.

**Comment by coriolinus** [comment]
This issue hasn't moved in half a year, but I believe that there is now a general consensus that exercises in this track should include stub implementations. 

Are there any objections to closing this issue, with the following policy?

- In general, Rust track exercises should include minimal stubs to allow running the tests.
- If there is pedagogical value in _not_ including a stub for a particular exercise, then we should include a `.meta/no-stubs` file explaining why
- In the future, we may choose to include a CI check which ensures that sufficient stubs exist to compile the tests for all exercises which do not have that file, but that will be at soonest a medium-term project.
