### ISSUE TITLE
Phone number unit test not conforming to README (and neither to NANP)

### ISSUE THREAD

**Issue by marcoesposito1988** [exercism/rust#310]
The README states (correctly according to the [NANP format](https://en.wikipedia.org/wiki/North_American_Numbering_Plan#Modern_plan) that the first digit of the Area and Exchange codes should be in the range 2-9 (so excluding 0 and 1).

However, the unit tests do not conform to this: invalid numbers (e.g. 1234567890) are supposed to be recognized as valid to pass the test. The example solution also does not conform.

Should I create a pull request with a correction or am I getting confused?

**Comment by petertseng** [comment]
You're absolutely right.

The options for the pull request are:

* Only change leading 1 and 0 to be invalid (change any tests/example that contradict this), nothing else.
* Additionally assure that the Rust track conforms to https://github.com/exercism/problem-specifications/blob/8756431983268d7c30e24463ef8aa0753c4ffab0/exercises/phone-number/canonical-data.json . (This is the common set of tests as of https://github.com/exercism/problem-specifications/pull/745). That would mean we'd be able to say 1.1.0 at https://github.com/exercism/rust/blob/master/exercises/phone-number/Cargo.toml#L3 instead of 0.0.0 (which means the Rust track's phone-number currently does not conform to any known problem-specifications version).
* Additionally assure that the Rust track conforms to https://github.com/exercism/problem-specifications/pull/772 (1.2.0).

Since you asked, you get to take the first pick of which of these options to take. If you would not, then other interested parties may as well.
