### ISSUE TITLE
Some tests for 'proverb' task does not seem to match assignment

### ISSUE THREAD

**Issue by andreyrubtsov** [exercism/rust#379]
Assignment says that the last line should be "And all for the want of a horseshoe nail.", but some tests actually require "And all for the want of a nail."

I think these tests should be fixed.

**Comment by petertseng** [comment]
I ask for leniency regarding my confusion, since I'm not familiar with this proverb.

What is even going on with these tests?

https://github.com/exercism/rust/blob/master/exercises/proverb/tests/proverb.rs#L13 says "// Notice the change in the last line at three pieces." and doesn't explain any logical reason why the last line should change at three pieces.

I see that the example derives it by using the first three elements of the list as in https://github.com/exercism/rust/blob/master/exercises/proverb/example.rs#L11 but this wouldn't work if we passed in (completely made up on the spot) `["bacterium", "stomach", "person"]` since then it would go "And all for the want of a personstomach bacterium" which is probably not a real term (though its meaning is probably understandable)

At least the https://github.com/exercism/ruby/blob/master/exercises/proverb/proverb_test.rb#L56 tests make it explicit that the extra word "horseshoe" should be specified as an input (I'm not going to check any of the other tracks that implement this exercise but they can be seen at http://x.exercism.io/problems/proverb) so uh maybe that's a possible solution?

Though really, given the description I don't see why I should be required to write a function that can accept multiple objects to insert into the proverb; I think I only need to output the proverb...?

I don't understand how this exercise is supposed to work.

**Comment by coriolinus** [comment]
@petertseng Agreed, we should probably clean these tests up.

FWIW, in the version of the nursery rhyme that I grew up with, the last line was simply "And all for the want of a nail." It fits better poetically, and has a great property for generating the proverb: it doesn't matter if you pass in `["nail"]`, `["nail", "shoe", "horse"]`, or whatever else; the last line simply needs to use the first input item. IIRC, I modified the tests when I actually did this exercise so that they all expected exactly that. 

I could put together a PR updating this within the next few days, but I don't think this is strictly a Rust issue; we'd want to update the upstream problem specifications, if we go that route. Should we open an issue/PR for that?

**Comment by petertseng** [comment]
Although there is no https://github.com/exercism/problem-specifications/blob/master/exercises/proverb/canonical-data.json, one might reasonably expect we can ask about https://github.com/exercism/problem-specifications/blob/master/exercises/proverb/description.md or ask in https://github.com/exercism/problem-specifications/issues/578 in preparation for when the canonical-data.json is made.
