### ISSUE TITLE
Excessively long struct name in rna-transcription

### ISSUE THREAD

**Issue by shingtaklam1324** [exercism/rust#407]
Currently, the `struct` names are `DeoxyribonucleicAcid` and `RibonucleicAcid`, which seem way too long and doesn't provide any useful information that `DNA` and `RNA` wouldn't provide to people without Biology / Chemistry backgrounds.

## Proposed Change
`DeoxyribonucleicAcid` => `DNA`
`RibonucleicAcid` => `RNA`

**Comment by coriolinus** [comment]
`DeoxyribonucleicAcid` is 20 chars. Do you have a reference for that being too long?

**Comment by shingtaklam1324** [comment]
It's not that it is _that_ long but rather that the extra information in the extended name doesn't do anything

**Comment by petertseng** [comment]
I think I usually keep code identifiers close to how I would speak, and when speaking it's very likely I only say DNA and RNA. Counterexampe: I've broken that rule, since I sometimes name variables similarly to `dist`, `pos`, `col`, `len`. Maybe my rule only works in one direction: my identifiers are no longer than how I would speak, but they might be shorter???

**Comment by coriolinus** [comment]
There are pressures in both directions. In a world where autocompleting code editors are ubiquitous, I often find that the clarity of a longer name more than offsets the slight additional typing burden it imposes. I'm very likely to name things with a short phrase when I can't think of a sufficiently descriptive single word; I'm somewhat less likely to abbreviate things unless there's a convention in favor of doing so.

That said, I agree that "DNA" and "RNA" are well-understood enough that there should be no real problem using those abbreviations instead of spelling everything out. However, I have no particular interest in doing the necessary work myself. @shingtaklam1324 are you interested in contributing a PR to make that change?
