### ISSUE TITLE
Wrong subheading in Simple Linked List

### ISSUE THREAD

**Issue by kedeggel** [exercism/rust#413]
In Simple Linked List's [Readme](http://exercism.io/exercises/rust/simple-linked-list/readme) is a mistake in a subheading. The correspondig Readme in git can be found [here](https://github.com/exercism/rust/tree/master/exercises/simple-linked-list#why-optionboxnode-and-not-just-optionnode). 

![issue](https://user-images.githubusercontent.com/17932749/33711701-28abf284-db45-11e7-90cd-9ce39c1d9855.PNG)

**Comment by coriolinus** [comment]
Interesting. The relevant HTML source looks like this:

```html
Why Option&lt;<strong>Box</strong>&lt;node&gt;&amp;gt;&amp;gt;
```

The string `&gt;&amp;gt;&amp;gt;` is particularly interesting because it implies that at some point in the Markdown -> HTML toolchain, an already HTML-safed version was re-HTML-safed. 

I don't personally know enough about the code which drives the exercism site to know where to start debugging this. @petertseng, @Insti do you have any ideas?

**Comment by petertseng** [comment]
Interesting, node got downcased and T disappears completely, unless my eyes deceive me.

> @petertseng do you have any ideas?

no

**Comment by Insti** [comment]
> @Insti do you have any ideas?

The malformed markdown file is here: https://github.com/exercism/rust/blob/master/exercises/simple-linked-list/.meta/hints.md

This file is only present in the rust track.

The `readme.md` is probably generated by `configlet`, I don't know if the Rust track documents this procedure. (The Ruby track does.)

Fix the `hints.md` file and regenerate `readme.md` and submit a PR with both changes.
