### ISSUE TITLE
Link to rust team page is broken

### ISSUE THREAD

**Issue by phansch** [exercism/rust#414]
Almost all of the exercises link to the [Rust Team Page](https://github.com/orgs/exercism/teams/rust), but the link returns a 404.

When I go to [orgs/exercism/teams](https://github.com/orgs/exercism/teams) it tells me `You’re not a member of any teams in this organization.`

[There's a bunch of exercises with the link](https://github.com/exercism/rust/search?utf8=%E2%9C%93&q=%22https%3A%2F%2Fgithub.com%2Forgs%2Fexercism%2Fteams%2Frust%22&type=)

I guess this could also be an issue with other language repositories?

**Comment by petertseng** [comment]
The intention behind putting that link there was good, but the execution could not match it, since teams are only visible to organisation members. GitHub probably has their reasons for doing this; maybe it simplifies logic of team views since some team members might choose not to publicise their membership.

I have two reasonable options to suggest:

1. Remove link with no replacement.
2. Replace link with https://github.com/exercism/rust/blob/master/config/maintainers.json.
3. Your suggestion goes here

**Comment by coriolinus** [comment]
I thought that the point of maintaining config/maintainers.json was that
exercism was going to put up a more human-friendly page built from that
data, at some point. (Possibly only in nexercism?) If anything, I'd point
the link there.

**Comment by Baelyk** [comment]
I hope this isn't considered grave digging, but

I think we should link to the [Getting Help](http://exercism.io/languages/rust/help) page on exercism.io.

Would that be a satisfactory solution?

In mentions the support Gitter which seems active enough and this issues page.

**Comment by petertseng** [comment]
That's an interesting choice that http://exercism.io/languages/rust/help chooses to link to https://github.com/exercism/exercism.io/issues instead of https://github.com/exercism/rust/issues but depending on the situation, either of the two might be appropriate.

I can't think of any reasons to strongly support or strongly oppose adding a link to http://exercism.io/languages/rust/help.

The link to https://github.com/orgs/exercism/teams was added in https://github.com/exercism/rust/pull/138 for the purpose of showing students the track. The link to the list of maintainers is not essential for that purpose (but may make the repo seem more desirable?). Since it doesn't work, we lose little by removing it. It should be removed. The text can stay, it just doesn't need to be a link.
