### ISSUE TITLE
Shouldn't Simple-linked-list Peak function return Option<T> instead of Option<&T>

### ISSUE THREAD

**Issue by Dimkar3000** [exercism/rust#416]
Still new to rust but for what i have gathered returning a reference is generally a bad idea. Shouldn't the peek function just return Option<T> with a copy of the value?

If so you will need to change the peek testcase too.

**Comment by coriolinus** [comment]
No: if it returned `Option<T>`, then `peek` would need to give away ownership of the contained object the way `pop` does. If it did that, then the next use of either `peek` or `pop` would be out of luck, because the list wouldn't own that object anymore. By returning a reference instead, the list retains ownership. 

In cases where `T: Copy`, you'd be able to get away with it, because the compiler clones the values under the hood. However, that would impose that type restriction on the list. In other words, you couldn't then have a `SimpleLinkedList<String>`, because `String`s are _not_ `Copy`. 

Returning references isn't inherently a bad thing; often, as in this case, it's the most reasonable way to get things done. However, this is one of the big differences between Rust and C: Rust keeps track of exactly who owns the object (in this case the `SimpleLinkedList`) and will refuse to compile if, say, you try to use a value which you acquired via `peek` after the owning list is destroyed. This makes it safe to use that reference, because you know it will always point to a valid value. C doesn't make that guarantee, so you have to do the work of ensuring that you never attempt to use an invalid peeked value on your own.

**Comment by Dimkar3000** [comment]
Thank you for the explanation I think I got it now :D
