### ISSUE TITLE
grade-school exercise return type signatures

### ISSUE THREAD

**Issue by derekdreery** [exercism/rust#425]
>    `// If grade returned an `Option<&Vec<String>>`,`
>    `// the internal implementation would be forced to keep a `Vec<String>` to lend out.`
>    `// By returning an owned vector instead,`
>    `// the internal implementation is free to use whatever it chooses.`

The correct return type is probably `Option<&[&str]>`, then the caller decides what to do with the result (clone it or not).

**Comment by derekdreery** [comment]
Actually, thinking about it, it would have to be a `Option<Vec<&str>>`, because you don't know the internal data structure, you can't hand out references to the lists of borrows.

**Comment by derekdreery** [comment]
Maybe it's not worth changing.

**Comment by coriolinus** [comment]
The correct type is `Option<Vec<String>>`.

If it were otherwise, we would have to prove to the borrow checker that the owned value in the `School` struct outlives the borrow. It's possible, but it's more advanced than the skill level at which this exercise is aimed. Also, it would force the implementation to keep such a value alive for that duration.
