### ISSUE TITLE
`crypto-square` exercise tests contradict `README.md`

### ISSUE THREAD

**Issue by Phippsaurus** [exercism/rust#458]
In the [`README.md`](https://github.com/exercism/rust/blob/master/exercises/crypto-square/README.md) for the exercise `crypto-square` it says:

> Output the encoded text in chunks.  Phrases that fill perfect rectangles
`(r X c)` should be output `c` chunks of `r` length, separated by spaces.
Phrases that do not fill perfect rectangles will have `n` empty spaces.
Those spaces should be distributed evenly, added to the end of the last
`n` chunks.

The [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/canonical-data.json) gives an example for this:

```json
    {
      "description": "54 character plaintext results in 7 chunks, the last two with trailing spaces",
      "property": "ciphertext",
      "input": {
        "plaintext": "If man was meant to stay on the ground, god would have given us roots."
      },
      "expected": "imtgdvs fearwer mayoogo anouuio ntnnlvt wttddes aohghn  sseoau "
}
```

Contrarily the [rust implementation](https://github.com/exercism/rust/blob/master/exercises/crypto-square/tests/crypto-square.rs) of that test looks like this:

```rust
fn test_example() {
    test(
        "If man was meant to stay on the ground, god would have given us roots.",
        "imtgdvs fearwer mayoogo anouuio ntnnlvt wttddes aohghn sseoau",
    )
}
```

I was about to create a pull request for that issue, but there are further discrepancies which are not quite clear. The rust tests strip numbers from the input, where the canonical data leaves them in. Furthermore the rust version strips non-ASCII characters, where the canonical data has no example for that case.

If somebody could clarify what the exercise is actually supposed to look like, I will adjust it accordingly.

**Comment by DanT-Git** [comment]
lines 50-52 in the README use the word "spaces" but really mean missing characters or short lines. The requirement is to distribute the jaggedness so the encoded rows at the bottom are at most 1 char short of the first row(s).

I had trouble with this, so I made my own `test_jagged()` test.  Your code fails these tests, btw:

```rust
test("aaaa bbbb cccc d", "abcd abc abc abc");
test("aaaa bbbb cccc dd", "abcd abcd abc abc");
test("aaaa bbbb cccc ddd", "abcd abcd abcd abc");
```

If I can figure out how, I will do a pull request with this clarification and added tests.

**Comment by Phippsaurus** [comment]
I appreciate you looking into this so quickly, but I think it would be less effortful to adapt the _Rust_ tests and example implementation, rather than changing the [`README.md`](https://github.com/exercism/rust/blob/master/exercises/crypto-square/README.md) which would affect all other language tracks as well.

For example, the [_F#_ version](https://github.com/exercism/fsharp/blob/master/exercises/crypto-square/CryptoSquareTest.fs) also tests for added spaces:

```F#
[<Fact(Skip = "Remove to run test")>]
let ``8 character plaintext results in 3 chunks, the last one with a trailing space`` () =
    ciphertext "Chill out." |> should equal "clu hlt io "

[<Fact(Skip = "Remove to run test")>]
let ``54 character plaintext results in 7 chunks, the last two with trailing spaces`` () =
    ciphertext "If man was meant to stay on the ground, god would have given us roots." |> should equal "imtgdvs fearwer mayoogo anouuio ntnnlvt wttddes aohghn  sseoau "
```

I can't color highlight here, but notice how the shorter blocks are padded with spaces in addition to those required to separate the blocks.
That is in accordance with the language-independent [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/canonical-data.json) and the [`README.md`](https://github.com/exercism/rust/blob/master/exercises/crypto-square/README.md) as well as [`description.md`](https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/description.md).

**Comment by emengd** [comment]
Hi, found this as I just did the exercise and saw the same problem.

It seems to me that the original Readme was very clear about what it wanted, and it's the tests that are wrong. Your new readme doesn't make any sense to me: if you add the last characters to the last chunks, they will be longer, not shorter than the first. What your tests instead enforce is that the last characters be added to the *first* chunks. Also, the phrasing as "extra" rather than "missing" characters suggest a different definition for r and c, though honestly attempting to completely think this through gives me a headache.* Anyway what your tests enforce is very much not what the original readme wanted, which is that spaces should be appended to the string so that it fills the rectangle, as you can see in the example.

(*In fact, but this is not specific to the Rust track I think, the Readme doesn't specify really explicitly how to choose r and c. What you have to pick is the smallest `(r, c)` that fits the message, which is reasonably easy to guess from the example. It is less easy to guess with your phrasing, because we're not sure anymore whether the r x c rectangle is the one that encloses the padded message, or the one that encloses the truncated message.)

**Comment by petertseng** [comment]
> The rust tests strip numbers from the input, where the canonical data leaves them in.

OK, I think the Rust test is in the wrong here. https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/description.md tells me that "the spaces and punctuation are removed from the English text", and I think we agree that a number is not a space or a punctuation. They should be left in.

> Furthermore the rust version strips non-ASCII characters, where the canonical data has no example for that case.

The Exercism-wide policy in https://github.com/exercism/problem-specifications/issues/428 would have us not use non-ASCII characters at all. In instances such as scrabble-score (https://github.com/exercism/rust/pull/421 and https://github.com/exercism/rust/pull/125) and reverse-string (https://github.com/exercism/rust/issues/428) we chose to contravene the policy where it is essential to the problem.

I do not think the behavior is essential to the problem, since the act of performing the transposition is the same no matter whether you are transposing individual bytes, grapheme clusters, or even any other data type that doesn't necessarily need to map to readable text.

I thus recommend those cases be removed.

> Phrases that do not fill perfect rectangles will have `n` empty spaces.
> Contrarily the rust implementation of that test looks like this:

I agree that the Rust implementation does not agree with the specification when dealing with trailing spaces.
I agree that the Rust implementation should be change such that it agrees with the specification.

**Comment by petertseng** [comment]
EBWODP:

> They should be left in.

This sentence is unclear. It should read: "Numbers should be left in the text. This means that any tests that expects numbers to be removed should be changed"

**Comment by petertseng** [comment]
The solution I suggested to spacing in https://github.com/exercism/problem-specifications/issues/190 was to remove all spacing so that the output would be "imtgdvsfearwermayoogoanouuiontnnlvtwttddesaohghnsseoau" but that horse has left the stable... for now. If there were a case for it, it could be changed.

**Comment by dantho** [comment]
I've come to appreciate @Phippsaurus 's OP.  I hope my eagerness to contribute hasn't muddied the waters too much.
@petertseng , I agree with your assessment and recommendations.  (But I think that "horse" at the bottom should be left in peace.  By that I mean cramming the encoded output into one long string without spaces looks _very_ confusing to me.)

At present, I have PR open against the specification, to clarify the [description.md](https://github.com/exercism/problem-specifications/pull/1210), and a [misguided PR ](https://github.com/exercism/rust/pull/459) open against Rust, which should probably just be rejected.  How do I revoke a PR?

**Comment by petertseng** [comment]
> How do I revoke a PR?

If you visit `https://github.com/exercism/rust/pull/459` (https://github.com/exercism/rust/pull/459) you should see a Close pull request button. It is at the bottom of the page in the browser.

**Comment by dantho** [comment]
Closed.  Thanks.
