### ISSUE TITLE
Travis allows merges which include overflowing literals

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#461]
This bit us in #440.

**Comment by shingtaklam1324** [comment]
One way to fix this would be to use `#![deny(overflowing_literals)]`

**Comment by petertseng** [comment]
I'd suggest to hasten the move toward the world where we check that all stubs compile without any warnings at all. This is a more long-term goal that encompasses this problem and maybe some others.

**Comment by petertseng** [comment]
> we check that all stubs compile without any warnings at all

We can have an useful intermediate state, where we do something similar to https://github.com/exercism/rust/pull/478 but only start out with `#![deny(overflowing_literals)]` instead of the wholesale `#![deny(warnings)]`.

Are there any other possible mistakes we might like to protect against?

I would accept something like https://github.com/exercism/rust/pull/478 that only adds `#![deny(overflowing_literals)]`, and then we can discuss what it takes to get to stubs with no warnings at all.

**Comment by shingtaklam1324** [comment]
A few lints that may be useful for some exercises, but not all:

- `missing-docs` could be useful to make sure all function signatures when provided are documented properly for the students
- `dead-code`
- `unreachable-code`
- `unused-mut`

The full list of `rustc` lints are available using `rustc -W help`
