### ISSUE TITLE
circular_buffer: Shall we remove `allow(unused_must_use)`?

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#475]
You will observe that https://github.com/exercism/rust/blob/master/exercises/circular-buffer/tests/circular-buffer.rs contains an `allow(unused_must_use)` to avoid compiler warnings (and thus a CI rejection, since our CI rejects warnings) from the fact that many Results from `write` are ignored.

Shall we instead use `let _ = buffer.write(...)` ?

The advantage is that it is more precise about exactly which lines are ignoring a `Result` rather than casting a wide net over the entire test module.

It would also allow us to remove an `mod tests` that is present in only circular-buffer probably for the sole reason of scoping the `#[allow(...)]`

The disadvantage is that since there may be other reasons to use `let _ = ...` it makes it hard to grep the entire repo to determine what's ignoring a Result and what is using `let _ = ...` for other reasons.

The `circular-buffer` was added in https://github.com/exercism/rust/pull/52 at which time there was no discussion of this point.

The other exercise that prominently uses `let _ = ...` is Bowling; the discussion may be seen around https://github.com/exercism/rust/pull/213#issuecomment-253384376 and a few surrounding comments (such as https://github.com/exercism/rust/pull/213#discussion_r83556987)

**Comment by coriolinus** [comment]
I think that `expect` is probably the best solution here, possibly with an explanatory comment to the effect of `we know this will succeed because we have perfect control of the test environment. expect is still not recommended for production code!` at the first instance. It's explicit and gets across the point that this isn't what the tests are intended to measure.
