### ISSUE TITLE
hamming/src/lib.rs template missing

### ISSUE THREAD

**Issue by BartMassey** [exercism/rust#509]
```Rust
/// Return the Hamming distance between the strings,                            
/// or an error if the lengths are mismatched.                                  
pub fn hamming_distance(s1: &str, s2: &str) -> Result<u64, ()> {
    unimplemented!("What is the Hamming Distance between {:?} and {:?}",
                   s1, s2);
}
```

**Comment by petertseng** [comment]
I wouldn't like use `()` in the `E` of `Result<T, E>`. I know, I know, it's just a stub, students can change it if they like, but since there isn't a need to, likely it won't happen.

I wonder if this should change to `Option` instead, since there is only one way it can error.

I guess if we really wanted, we can do something like `enum Error { LeftTooLong, RightTooLong }`, but that seems contrived.

**Comment by BartMassey** [comment]
Yeah, I'm not sure why `Result` was pulled out here. I'd probably change it to `Option`. If you're going to return an `Error`, it should probably be a `std::error::Error` with the machinery that implies.

In general, there are a lot of functions in these problems that I wouldn't make total. An `assert!()` with a negative test would be more my taste for a lot of them, including this one. Although one of the tests earlier actually checked the assertion string, which seems a little over the top especially since it wasn't documented.
