### ISSUE TITLE
Armstrong numbers readme typo

### ISSUE THREAD

**Issue by sputnick1124** [exercism/rust#526]
In the README for the armstrong numbers exercise (https://github.com/exercism/rust/blame/master/exercises/armstrong-numbers/README.md#L8)
`10 != 1^2 + 0^2 = 2`
is not true. Rather it should be
`10 != 1^2 + 0^2 = 1`
correct? 

Either way, 10 is obviously not an Armstrong number, but the error is apparent.

**Comment by coriolinus** [comment]
@sputnick1124 With https://github.com/exercism/problem-specifications/issues/1236 resolved, the only work necessary to fix this issue is to create a branch and rerun `configlet generate . --only armstrong-numbers`; that command rebuilds the README based on the specifications. Would you be willing to create that PR?

**Comment by sputnick1124** [comment]
Sure thing! Thanks for the opportunity! I'll let you know if I have any problems.

**Comment by sputnick1124** [comment]
Fixed in https://github.com/exercism/rust/pull/531
