### ISSUE TITLE
Feedback: Simple Linked List exercise feels like a big leap from previous exercises

### ISSUE THREAD

**Issue by radiofreejohn** [exercism/rust#554]
I just wanted to add some feedback about this exercise. Most of the exercises leading up to this one don't involve a lot of quirks about Rust's borrowing semantics or generic types, so the exercise feels pretty difficult.

In fact, I think it's remarkably difficult without a decent build up – so difficult there is a series of long posts about how annoying linked lists are in Rust: http://cglab.ca/~abeinges/blah/too-many-lists/book/

Also, the solutions there appear to mirror the exercise almost exactly, except for the exercism one uses `data` and that blog post uses `elem` – In order to really understand the hows and whys, you kind of need to read that entire blog post, at which point, you have the solution handed to you.

I think that a few exercises that cover a simpler case of borrowing and lifetimes, as well as a simpler exercise for generics would be a better lead in to the simple linked list exercise.

I'm pretty new to Rust, but if I can think of a decent enough exercise for one or both of these I'll try to submit a PR, but I think it's probably better if someone else does, assuming there is any agreement on my feedback. If not, that's OK too :)

**Comment by coriolinus** [comment]
We've tried to flesh out the README with some detailed hints about how to approach that exercise, though it sounds like we didn't cover all your questions. 

We're always glad to review PRs which add exercises; some difficulty 4 ones introducing generics, borrowing, and lifetimes could definitely help. Don't be afraid to take a shot at building them. Even if all you can do is to flesh out the README in that exercise a bit, we'd be happy for the contribution.

I'm going to close this issue now, not because I disagree with your feedback, but because there's not really a call to action here: I don't have an unused generic-teaching exercise in my back pocket either. Feel free to reopen if you feel there's more that needs to be said.
