### ISSUE TITLE
Fix getting started instructions for rust

### ISSUE THREAD

**Issue by jackhughesweb** [exercism/rust#599]
Some exercise README templates contain links to pages which no longer exist in v2 Exercism.

For example, C++'s README template had a link to /languages/cpp for instructions on running tests. The correct URLs to use can be found in the 'Still stuck?' sidebar of exercise pages on the live site. You'll need to join the track and go to the first exercise to see them.

Please update any broken links in the 'config/exercise_readme.go.tmpl' file, and run 'configlet generate .' to generate new exercise READMEs with the fixes.

Instructions for generating READMEs with configlet can be found at:
https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md#generating-a-readme

Instructions for installing configlet can be found at:
https://github.com/exercism/docs/blob/bc29a1884da6c401de6f3f211d03aabe53894318/language-tracks/launch/first-exercise.md#the-configlet-tool

Tracking exercism/exercism.io#4102

**Comment by coriolinus** [comment]
```sh
$ for url in $(rg -ioN 'http[^\s)]+' config/exercise_readme.go.tmpl); do
>   echo "$url"
>   curl -IL "$url" | rg HTTP
> done
Fri Aug 31 02:05:48 DST 2018
https://doc.rust-lang.org/book/second-edition/ch07-00-modules.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 23810    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
https://github.com/exercism/rust
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
HTTP/1.1 200 OK
https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/README.md
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
HTTP/1.1 200 OK
http://exercism.io/languages/rust
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   170    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   170    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 302 Moved Temporarily
HTTP/1.1 302 Moved Temporarily
HTTP/1.1 200 OK
https://doc.rust-lang.org/book/second-edition/ch07-00-modules.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 23810    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
https://doc.rust-lang.org/book/second-edition/ch14-00-more-about-cargo.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 23143    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
https://doc.rust-lang.org/book/second-edition/ch11-02-running-tests.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 34764    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
```

Looks like everything is fine here.

**Comment by petertseng** [comment]
Well the 302 is interesting isn't it. There is the http://exercism.io/languages/rust which claims to be a help page, but isn't really. Compare to https://web.archive.org/web/20180219222916/http://exercism.io/languages/rust . Okay, that tells me that also used to redirect to http://exercism.io/languages/rust/about . So that used to be https://web.archive.org/web/20180219222916/http://www.exercism.io/languages/rust/about . 

Where is that link used? The context is `Refer to the [exercism help page][help-page] for Rust installation and learning resources.`

Okay, well, I observe that:

* the old link (a redirect to http://exercism.io/languages/rust/about ) was not *directly* helpful (the student still has to follow the sidebar links to the installation and learning resources)
* neither is the new link. It redirects to https://exercism.io/my/tracks/rust for a logged-in person and the student must find and follow the links under Guides to get tot he claimed installation and learning resources

So we do not suffer from the problem a page not existing, so I think it is correct to close this issue.

But if someone were to suggest an improvement to the template, it would be to do one of two things:

* Explicitly say that the guides are located under *Guides*
* Directly link to the relevant guides we wish to call out.

If someone thinks these suggestions are worth making, this person should make an issue or pull request about it as appropriate.

**Comment by jackhughesweb** [comment]
@coriolinus Could the 302 be changed to point to one of the new help pages (such as `https://exercism.io/tracks/rust/learning` - other help pages have links to them at the bottom of that page), and regenerate the config files using `configlet generate .`? 

The new Exercism no longer has help information on the track page, and the following link to the old help information may cause confusion to new people joining the track:

https://github.com/exercism/rust/blob/0fbbcba7e6152c78c9d2d9bea707a23b44b14974/config/exercise_readme.go.tmpl#L55

Sorry for any confusion 😄
