### ISSUE TITLE
Should rustfmt and clippy checks be added to the CI?

### ISSUE THREAD

**Issue by ZapAnton** [exercism/rust#659]
The [README for submitting PR](https://github.com/exercism/rust#submitting-a-pull-request) states that the submitted code should be formatted  with `rustfmt`.

Since there is already a [script](https://github.com/exercism/rust/blob/master/bin/format_exercises) that is used to format existing exercises, should it be used in the Travis CI to check the format of the submitted code?

Also as of Rust 1.29 the `cargo clippy` command works on stable. Should it also be used in Travis to ensure that the submitted code is idiomatic?

**Comment by petertseng** [comment]
clippy would be exciting. Might be time to bring back https://github.com/exercism/rust/pull/445 . As of this moment I can't get it to run on the tests, so I guess it'd just be the examples and stubs? That's a bit of a shame. Want to hear solutions.

**Comment by ZapAnton** [comment]
`cargo clippy --all-targets` seems to be working on the whole crate

**Comment by ZapAnton** [comment]
I have run a simple script over the existing exercises:
```shell
   1   │ #!/bin/bash
   2   │ 
   3   │ for dir in exercises/*; do
   4   │         (
   5   │                 cd "$dir"
   6   │ 
   7   │                 cargo clippy --all-targets
   8   │         )
   9   │ done
```

clippy managed to check the `src/lib.rs` and `tests/exercise-name.rs` but could not check `example.rs`.
Perhaps another point in favor of #658?

**Comment by petertseng** [comment]
I have great news to share: Clippy is now being enforced by CI, on the tests only.

Yet to be done is:

* Clippy on the stubs (won't be able to do this for stubs that are allowed to not compile, but can be considered for stubs that do)
* Clippy on the example solutions (pretty low priority IMO, and I'd probably close this issue even if that was not done)
* rustfmt

**Comment by petertseng** [comment]
Regarding example solutions: with the merging of https://github.com/exercism/rust/pull/1009, now we enforce that there are no Clippy *errors* in the example solutions, but we still allow Clippy *warnings*.

**Comment by petertseng** [comment]
Rustfmt has been added to CI. Now I am considering what, if anything, to do about the remaining Clippy warnings in examples and stubs.

One approach I'm thinking of: add attributes that allow only the specific warnings that currently exist, and deny all others. For the example solutions the attributes can probably just be added in directly. For the stubs, since it'd probably be weird to distribute the attributes to students, so I'm thinking it's possible to add the attributes only at test time like the deny warnings attributes are. This approach would prevent further warnings from being added, and the current ones can either be kept or not, depending on what is appropriate. I will give it some more thought in the coming days.
