### ISSUE TITLE
Bug in "Series" side exercise test?

### ISSUE THREAD

**Issue by mboersma** [exercism/rust#671]
The [first test case](https://github.com/exercism/rust/blob/master/exercises/series/tests/series.rs#L4-L7) to the "Series" side exercise expects a Vector of six empty strings to be returned for the input "92017" and length 0.

How can this be the expected output from a five-digit input? The exercise doesn't specify behavior when the substring length is 0--I would have expected an empty Vector to be returned in this case. Or maybe a Vector of 5 empty strings.

I don't see any tests specifying substring length 0 for the same exercise in the Go track. I think this test case is wrong, or else I'm missing something.

**Comment by coriolinus** [comment]
Not a bug: this is the [behavior as designed](https://github.com/exercism/rust/pull/402#discussion_r153480774).

**Comment by facundoolano** [comment]
I find this confusing, and I'm not the only one according to what I see in the comments of the community solutions.

I don't think the rationale in the linked comment follows from the contract of the function or the description of the problem. At the very least a comment in the test would help, but I'd personally consider zero length as invalid input.

**Comment by facundoolano** [comment]
To further back my rationale here, I think a very a natural way to solve this exercise is to use the [windows method](https://doc.rust-lang.org/std/primitive.slice.html#method.windows), which considers that a window of zero length as invalid input.

**Comment by facundoolano** [comment]
To further back my rationale here, I think a very a natural way to solve this exercise is to use the [windows method](https://doc.rust-lang.org/std/primitive.slice.html#method.windows), which considers a window of zero length as invalid input.

**Comment by coriolinus** [comment]
If the entirety of this exercise were to write `digits.windows(len).collect()`, there would be no point; the thing would be too easy. It would take longer to download the exercise and open the editor than to solve it. That just wouldn't be fun.

Our solution was to impose this requirement.  It can still be accomplished in just a few lines of code, it is entirely compatible with `windows`, and it is defined such that the entirety of the input domain maps to a valid output. 

I'm willing to review a PR adding a `.meta/hints.md` file, which extends the description of the problem. I would be disinclined to approve a PR changing the signature of the function required by this exercise.

**Comment by facundoolano** [comment]
> If the entirety of this exercise were to write digits.windows(len).collect(), there would be no point; the thing would be too easy. It would take longer to download the exercise and open the editor than to solve it. That just wouldn't be fun.

I disagree with this, as someone just starting out with the language, it is useful for me to get familiar with iterator methods, closures and such, especially in the first exercises. But I understand this is subjective (as is your definition of fun) and not the issue in question.

> I'm willing to review a PR adding a .meta/hints.md file, which extends the description of the problem. I would be disinclined to approve a PR changing the signature of the function required by this exercise.

I won't send a PR with an explanation because I honestly can't provide one. I don't follow the reasoning behind that test, and as I mentioned there's a lot of people complaining about the same, which should be a sign that this isn't intuitive:

https://exercism.io/tracks/rust/exercises/series/solutions/e433faa03dcf458393116352fb429c89
https://exercism.io/tracks/rust/exercises/series/solutions/5960d2dae15f43acac4006c7d8b458e3
https://exercism.io/tracks/rust/exercises/series/solutions/2a75fe8b03f244639d89715f6d123d90
https://exercism.io/tracks/rust/exercises/series/solutions/6a44914026774a68b5fdc150ec3fe258
https://exercism.io/tracks/rust/exercises/series/solutions/54a781228fa542ec90f5f5a4c454ecf5
https://exercism.io/tracks/rust/exercises/series/solutions/43d38c061798486f93d217c0f4417706
https://exercism.io/tracks/rust/exercises/series/solutions/c41dd3533c0248dc89960e2278084494

**Comment by petertseng** [comment]
One observation from looking at the linked solutions:

Some solutions always have `6` elements instead of `len() + 1`. So if span of 0 continues to be tested, it would be wise to test it with multiple input lengths.

**Comment by coriolinus** [comment]
Agree, that would probably help make it clearer to the students.

**Comment by filakhtov** [comment]
I have [commented on the original PR](https://github.com/exercism/rust/pull/402#discussion_r1332978661) and just discovered this thread too. Considering every other language throws or returns the error I don't see why Rust should be deviating from that.

**Comment by senekor** [comment]
@filakhtov instead of necroposting, consider opening a new issue in the future. (Or rather, make a post on the forum, because that's where Exercism community discussions are happening.)

My immediate reaction is that this is simply not important enough to break all existing solutions.

The instructions state:

> And if you ask for a 6-digit series from a 5-digit string, you deserve whatever you get.

I'd say the current state is consistent with that vague description.

Please post on the forum if you want to discuss further.
