### ISSUE TITLE
What is the rational behind this commit? I would expect a u8 because you can't rotate negative.

### ISSUE THREAD

**Issue by hellow554** [exercism/rust#782]
What is the rational behind this commit? I would expect a u8 because you can't rotate negative.

_Originally posted by @hellow554 in https://github.com/exercism/rust/commit/1aedb76846f954efc98271818e3c5f372f467caf

CC @ZapAnton

**Comment by ZapAnton** [comment]
The main rationale for the commit is [this comment](https://github.com/exercism/rust/pull/567#discussion_r200083738) made by @coriolinus.

The purpose was, at least for me at the time, to give a student a chance to learn about the difference between signed/unsigned types and how to build / handle different APIs, built using these types.

Guess the above reasoning may sound too far-fetched, so perhaps if you discuss the input type with the maintainers, it could be changed back to `u8`

**Comment by hellow554** [comment]
Thanks for the explanation. Yes, I would argue, that a `u8` would fit way better here. It's a bit weird to write `c as u8 as i8` 😄 .

**Comment by coriolinus** [comment]
>  I would expect a u8 because you can't rotate negative.

Why can't you rotate negative? That just means left rotation, instead of right rotation.

**Comment by ZapAnton** [comment]
https://github.com/exercism/problem-specifications/pull/1438 has been closed without merging, which means we are free too implement additional negative shift test cases ourselfs, without syncing with the `problem-specifications` repository. I will try to make a PR in the near future.
 
There is  one point of concern though.  The linked PR was closed, because the maintainers believed that these particular test cases would make the exercise more difficult and frustrating for the students. If we are too add the tests, should we mark them in some special way, so students may skip them, if they want to (feature-locked tests, comments in the code, section in the README, etc.)?

@coriolinus may I ask for you opinion on the above moment?

**Comment by coriolinus** [comment]
I don't believe it is necessary to feature-lock these tests. In my opinion negative numbers here are not an advanced concept. 

If mentors discover a trend otherwise, we can revisit this issue in the future.
