### ISSUE TITLE
saddle-points: worst possible practice

### ISSUE THREAD

**Issue by michalfita** [exercism/rust#787]
The `saddle-points` problem uses matrices, which are part of algebra. Any programmer doing algebra seriously knows that _vector of vectors_ is the worst possible implementation of a matrix due to cache locality issues (doesn't apply to fixed array of fixed arrays).

Usage of vector of vectors (`vec![vec![], vec![], vec![]];`) teaches young adepts of programming bad practices. The correct ways to represent matrices are:

1. Use algebraic crate that handles matrices correctly and optimally (that would give a hint how address algebraic problems in general)
2. Use type holding one vector and dimensions and then implement access (that would give hint some other extensions to the type can be added, like column slice)
3. Use linear vector and pass matrix dimensions' sizes as another argument (that would be the most C-like way, however still valid)

That's my second exercise on [excercism.io](https://exercism.io/profiles/Manneveru), and I'm hugely disappointed.

I'm happy to provide a PR, but consensus is required which approach to choose.

**Comment by coriolinus** [comment]
I don't dispute that a vector of vectors is a suboptimal choice for high-performance matrix algebra. You're right! However, I think you've misunderstood the purpose of the saddle-points exercise. This exercise is designed to help students understand basic concepts about vectors, such as indexing, and that nested datatypes are legal. 

I would welcome a PR introducing a new exercise at a more advanced point in the track requiring students to implement a structure like suggestion 2; it sounds like it would be an interesting exercise, which once implemented, could be genericized into the general-purpose problem specifications. 

Closing because the early exercises such as saddle-points are meant for students learning Rust as a first language, who need introduction to the concepts in this exercise.

**Comment by michalfita** [comment]
Valid points.

Now, could I at least request to include a note in the exercise description, that would shortly summarize what you've just written above and underscore the vector of vector is inefficient and shouldn't be use in real life???

**Comment by coriolinus** [comment]
I'd be positively inclined toward a PR adding such a note. The simplest way to add it would be to create a `.meta/hints.md` file within the exercise folder, then regeneate the README using configlet.
