### ISSUE TITLE
luhn-trait description has dead link to wrong information

### ISSUE THREAD

**Issue by BartMassey** [exercism/rust#845]
The `luhn-trait` exercise description has a dead link to an old version of the Rust Book at "It is not idiomatic Rust to implement traits on on primitives." I think this is wrong in any case, as extension traits are pretty common: probably easiest to just delete the sentence. There's a good discussion of extension traits [here](http://xion.io/post/code/rust-extension-traits.html), but I am skeptical of linking to someone's blog post.

**Comment by petertseng** [comment]
Since the text is present in https://doc.rust-lang.org/1.14.0/book/traits.html but absent in https://doc.rust-lang.org/1.15.0/book/traits.html it is clear that the authors of the book decided that the book need no longer render judgment on whether the stated action is idiomatic.

I recommend the sentence be removed.

The person who wants to remove it would remove it from https://github.com/exercism/rust/blob/master/exercises/luhn-trait/.meta/description.md and https://github.com/exercism/rust/blob/master/exercises/luhn-trait/README.md.
