### ISSUE TITLE
Bob: Add test to verify that mentee handle non ascii characters

### ISSUE THREAD

**Issue by gaetanww** [exercism/rust#875]
The tests don't verify that the mentees handle non ascii characters. Would it be possible to add that kind of test?

**Comment by coriolinus** [comment]
It's possible, but I'd be disinclined to merge such a test. This is for two reasons:

- Exercism has a policy that exercises should test only ascii strings unless there is a particular reason to test unicode. Lots of exercises have string inputs, but for most of them, the point is not string validation. `reverse-string` has some unicode tests, because it is materially of interest to the test. It's less clear that unicode tests would add anything to `bob`.
- Rust makes it difficult to do the wrong thing, unicode-wise, with an `&str` input. I can't offhand think of a reasonable example of how a student could fail suhc an additional test.

**Comment by coriolinus** [comment]
Closing because I believe this proposal has been answered completely. If you have further questions or rebuttals, please feel free to reopen.

**Comment by gaetanww** [comment]
I didn't know about that policy. I'll just play the devil's advocate for a second.

> Rust makes it difficult to do the wrong thing, unicode-wise, with an &str input. I can't offhand think of a reasonable example of how a student could fail suhc an additional test.
- I have seen mentees use is_ascii_uppercase() which wouldn't validate for input Ü (extended ASCII) for example.
- if Rust makes it difficult to do wrong thing Unicode wise, it is an even better reason to add test cases, because it shows that mentees are misusing it.
- ATM we're not testing ASCII string, but we're testing 'weird' strings like "22!%£2&?" Which actually forces mentees to handle weird edge-cases in a non intuitive way (using string.chars().filter(is_alphabetic).all(is_uppercase) does not actually work because of this arbitrary choice).

Sorry for the lack of formatting, I'm on my phone :)
