### ISSUE TITLE
What was it like to learn Rust?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/rust#882]
We’ve recently [started a project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation) to find the best way to design our tracks, in order to optimize the learning experience of students.

As a first step, we’ll be [examining the ways in which languages are unique and the ways in which they are similar](https://github.com/exercism/exercism/issues/5059). For this, we’d really like to use the knowledge of **everyone** involved in the Exercism community (students, mentors, maintainers) to answer the following questions:

1. How was your experience learning Rust? What was helpful while learning Rust? What did you struggle with? How did you tackle problems?
1. In what ways did Rust differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Could you spare 5 minutes to help us by answering these questions? It would greatly help us improve the experience students have learning Rust :)

_Note: this issue is **not** meant as a discussion, just as a place for people to post their own, personal experiences._

_Want to keep your thoughts private but still help? Feel free to email me at erik@exercism.io_

Thank you!

**Comment by Aloso** [comment]
When I started learning Rust, I knew Java, Javascript, PHP and very little C. I started with reading "The Rust Programming Language", which is a great book. I soon wanted to try out things, but the compiler kept rejecting my code. I added lots of lots of lifetimes, until I gave up after a few weeks (thanks to non-lexical lifetimes, this is less of a problem now).

When I heard about Exercism, I gave Rust another shot and went through the Rust track (the mentoring system didn't exist then). Also, I read online articles to try to better understand Rust's memory model. Exercism is the reason why I love Rust!

> What was hard to learn?

Ownership and lifetimes was the hardest part. Getting a good grasp of how traits work, and how to use them effectively, took some time. I also found generics, macros and the module system difficult (the module system was simplified in the 2018 edition).

> In what ways did Rust differ from other languages you knew at the time?

Besides the memory model, the biggest differences were the trait system, algebraic data types, pattern matching and the lack of inheritance and exceptions.

Rust has first-class Unicode support. Strings are UTF-8, so they can't be indexed in constant time. But they work well together with the `Iterator` API.

Rust makes a lot of things explicit: Error propagation, typecasts, dynamic dispatch and heap memory allocation.

> What did you have to unlearn?

OOP. Rust doesn't allow shared mutable state (unless you use `Cell`/`RefCell`), so many object-oriented practices are not feasible, a more “functional” approach is often better.

**Comment by kotp** [comment]
I believe the book referenced is here, if that helps anyone: https://doc.rust-lang.org/book/title-page.html

**Comment by efx** [comment]
Thank you for taking on this epic effort!
I had promised to reflect on my learning experience to @coriolinus and here seems fitting. Here goes my Rustacean Bildungsroman.

> How was your experience learning Rust?

I started learning Rust by attending a casual meet up in early 2018. I conversed with other Rust users and learned about some *whys* of the language and surrounding culture. There I acquired one motivation to learn Rust: becoming a "better programmer". I also heard about exercism.io from an attendee.

While I continued to dabble writing lame, personal software in Rust and read through the Rust programming book I did not commit to serious study of Rust until a few months ago.

> What was helpful while learning Rust? ... How did you tackle problems?

Using exercism to learn Rust has been an incredibly helpful [Ulysses pact](https://en.wikipedia.org/wiki/Ulysses_pact). I'll tersely summarize key resources for me:

- a print copy of [Programming Rust](http://shop.oreilly.com/product/0636920040385.do)

*Offline* documentation for
- ["the standard library"](https://doc.rust-lang.org/stable/std/index.html)
- ["The Rust Programming Language"](https://doc.rust-lang.org/stable/book/index.html)
- [Rust By Example](https://doc.rust-lang.org/stable/rust-by-example/)

Practice:
- exercism track core and side exercises
- implementing rosetta code exercises. (Andy Russells' (@euclio) excellent [search tool](https://acrussell.com/rosetta-coverage/) to find new problems)
- poring through existing [rosetta code implementations](https://github.com/rust-rosetta/rust-rosetta)
- Random other OSS contributions
- mentoring in the Rust track mentor ("Lernen durch Lehren")

Knowing I can ask [questions](https://users.rust-lang.org/u/efx/activity/topics) and receive prompt, thoughtful responses in the [discourse forum](https://users.rust-lang.org/) has been invaluable. I practice in starts and fits. If I run into a wall I often take a break and come back to it when I have free time to focus.

> What did you struggle with?

Some of the early exercises I tried on exercism seemed more maths focused. I consider myself more on the linguistic side of programming so I struggled with one early on and it impacted my motivation. (pythagorean triplet).
I have also struggled with finding the time to dedicate to applying concepts I have been learning through the above resources. I also struggle with motivation in general.

> In what ways did Rust differ from other languages you knew at the time?

I write JavaScript professionally and a hodgepodge of other things to keep web applications running (shell, configuration, GNU/Linux).

Rust makes me think more about software I write because of an emphasis on correctness. Because it puts the author in control of memory I need to model data structures and design patterns differently. JS/ES lets you do anything but you pay the costs later in large systems. While I've not authored large systems in Rust I find it requires more discipline from the author and can produce better designed software from compiler coaching and a strong type system.

> what was hard to learn?

- Intuiting the ownership model
- lifetimes
- number of concepts and implicit behaviors to acquire fluency


> What did you have to unlearn?

JavaScript runtimes are like training wheels when it comes to memory management. *No worries, the GC will take care of it...* I have had to unlearn not thinking about memory and the design tradeoffs that come with this approach. I have also had to unlearn a "write first, design later" method for creating software.


> What syntax did you have to remap?

Both are in the C lineage syntactically so visually felt familiar. I've not worked in strongly typed languages or much TypeScript so Rust's type system has been my first serious introduction.

> What concepts carried over nicely?

- language fluency
- Closures
- some functional programming techniques
- the productive power of defaults for author expressiveness and brevity ([ember.js](https://emberjs.com/))

I'm still learning Rust too. Don't ask me to write a macro.

**Comment by workingjubilee** [comment]
I consider myself a student! Also, uh, am doing exercises still... that sort of thing.

>How was your experience learning Rust? 
Challenging!

>What was helpful while learning Rust?
A lot of reading the book, and a lot of getting specific interactions on how things are done, and a lot more reading code. I find reading other people's code in Python and JavaScript (which I knew before to be actually not as helpful compared to reading other people's code in Rust, because JS and Python are so highly expressive that programs are very personalized. However, being less expressive (and therefore more powerful), patterns in Rust are much more... pattern-y?

>What did you struggle with?
Strings. Types. Laziness of iterators.

>In what ways did Rust differ from other languages you knew at the time?
Strongly typed. Less expressive. Affine typing, with its lifetimes and ownership, exists almost nowhere else, anyways, but strong types in general. The model for structs and traits, also.

>What was hard to learn?
Types and when you can and can not get inference, and how other languages do more coercion between types automatically. Yet, Rust was still the first language that I really started to grok types with, the power of `borrowck` helped get me over the edge there (I have largely found `borrowck` to be an aid, not a foe, but then, I've only worked with Rust as of this year). But definitely types, especially the nuances around string types.

Lifetimes also. I only so-so grasp them still.

>What did you have to unlearn? What syntax did you have to remap?
Speaking of maps, in JS and Python, map is eagerly evaluated, whereas it just creates a lazy iterator in Rust. This was actually a big stumbling point. For me this is where a lot of the early difficulty in the language hit from: early on you run into iterating over String or &str or, best of all, both and casting between, and then you slam right into
1) iterator laziness
2) types
3) borrowed lifetimes

I was going to mention I only have a vague idea of how traits even work but I spent approximately the last 72 hours staring literally at the exact code for reconciling Traits and Types and I think I kinda get it!

>What concepts carried over nicely?
Once I got used to iterator laziness I became very comfortable with it because a lot of Rust supports the "functional" style of expression very well which I had gravitated to very early on? But I think this is an individual thing. Dabbling with Elixir helped here. Elixir (case / cond) statements quickly became match, in my head, and even with those, I could see how they could be formulated from a further generalization of, sway, JS' switch.

**Comment by NobbZ** [comment]
> How was your experience learning Rust? What was helpful while learning Rust? What did you struggle with? How did you tackle problems?

In the beginning I massively struggled with lifetimes in rust, and usually I cancelled any efforts once I hit the first lifetime error.

In most recent versions, its not a problem anymore though, but maybe, its just that I'm thinking differently by my own in the meantime? I did a 2 year pause inbetween…

Also I think advent of code and exercism helped me a lot to get used to rust more.

> In what ways did Rust differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Rust has explicit mutability, which means, when I pass something to a function or I call a method on data, I will know in advance, that it might get mutated, because its in the type of the function/method I call.

**Comment by felix91gr** [comment]
I might come back to this to write a few more stuffs. Things are quite hectic around here in Chile so I don't have much time to write up all of the points I'd like. That said, let's get to the one thing I have thought about a lot.

Learning Rust has been like learning to program again. 

Not in the sense of the functional paradigms it has throughout the language. Nor in the sense of the incredibly awesome package manager it has. Or the awesome macros. Those are all things that other languages I've used do have, in better or worse form than Rust does.

No, Rust has been like learning to program again because of the **lifetime**. The concept of a lifetime is a new _Kind_ for me, in the type theory sense. No other programming language I've used has a direct concept of "who's the owner of this memory?", "who can use this memory right here and now?" or "do these two pieces of memory alias at all?". None of them do. 

It's been the hardest PL for me to learn vs hours invested in it, but that makes sense: it's after all, a new way of programming for me. It's like learning classes again with Java, in my Intro to Programming course. Or learning Generics, Function Pointers, Type Classes, etc. It's an entirely new _dimension_ of logic in the language. Not an expansion of the Type dimension (like for example Const Generics will be in Rust soon), no. It's a new one. That has been by far and away the most learning I've had to do with Rust, and the one thing no other language has asked of me before.

What a beautiful journey. I have tons more to go through, but I'm learning a lot. This language is super cool <3
