### ISSUE TITLE
Misleading or incorrect description of total order in `Poker`

### ISSUE THREAD

**Issue by adlerd** [exercism/rust#964]
The `Poker` problem claims:

> Poker hands do not conform to a total order

But this is inaccurate. Poker hands *are* naturally totally ordered, which [is defined](https://en.wikipedia.org/wiki/Total_order) as a partial order where all elements are pairwise comparable. (This is the same Wikipedia link provided in the docs for `Ord`!) What's odd about poker hands compared to (say) integers is that the equivalence relation induced on this order is not the identity, but a more relaxed equivalence.

How is this relevant for Rust and the problem?[0] It's perfectly alright to implement `Ord` for a type representing poker hands, *as long as `PartialEq`/`Eq` is defined compatibly*. Claiming otherwise is just confusing and I'm sure we can agree that `PartialOrd`, `Ord`, `PartialEq`, and `Eq` don't need *our* help in being confusing for newcomers, they're accomplishing that just fine on their own thank-you-very-much.

This isn't just a theoretical concern. I think the problem is best solved by deriving `Ord` and all its prerequisites on a suitably defined type and using `sort`; enough said. Maybe that makes the problem not useful for its intended lesson; that's a bigger question I don't have the context to tackle.

[0] Well, other than making the problem and the language accessible to anyone with a math background, which is pretty important in itself!

**Comment by coriolinus** [comment]
>  It's perfectly alright to implement `Ord` for a type representing poker hands, as long as `PartialEq`/`Eq` is defined compatibly.

This is true as far as it goes, looking only at the requirements of the traits involved. However, it's bad software engineering to define `PartialEq`/`Eq` such that they are true for equivalent but unequal hands. What happens if you then want to use a hand as a key in a hashmap, i.e. to keep track of statistics about which particular hands win most often? You either have to implement `Hash` in a compatible way, which is going to be tedious and also throw away a lot of information, or you have to go back to a more strict definition of equality. 

It's not a big deal for an exercism problem, which people generally write once and never touch again, but most non-trivial software is written over the span of months or years, often by more than one developer. Will the new junior guy notice the documentation that for a given type, equality is actually equivalence? Probably not. Can it come back to bite you in the future? Yes, absolutely. And what happens when you for some reason need to test for actual equality? You end up with a `.really_equal(&self, other: &Self) -> bool` method. It gets ugly. 

Besides, it's useful to practice correct engineering on toy problems such as Exercism's. If you hold yourself to professional standards in trivial exercises, then it's much easier to maintain them in professional work.

---

> Poker hands are naturally totally ordered

From a more mathematical perspective, I think this assertion is incorrect. We can both agree that there are a large number of hands in poker which are equivalent but unequal. If you and I have hands whose ranks are all identical, then sure, we'll split the pot. However, our hands are unequal because our matching cards at each rank necessarily have different suits. This violates the antisymmetry property:

> If `a ≤ b` and `b ≤ a` then `a = b`

Our hands satisfy both properties `a <= b` and `b <= a`, but they do not have the property that `a == b`. Therefore, they do not have a total ordering.

---

> How is this relevant for Rust and the problem? ... I think the problem is best solved by deriving `Ord` and all its prerequisites on a suitably defined type and using `sort`

There's a better solution:

- construct a `HandRank` type. It doesn't really matter what the type is; C programmers might make it an integer, but I prefer something like this:

   ```rust
   enum HandRank {
     FourOfAKind,
     StraightFlush,
     /// etc
   }
   ```

  (It might need a little more complication to handle the high-card fallback, but that's just details.)

- impl `PartialOrd` and `Ord` for `HandRank`
- impl a method on the `Hand` type: `fn rank(&self) -> HandRank`
- `hands.sort_by_key(|hand| hand.rank())`

This is not substantially more work than implementing `PartialOrd`, `Ord`, and `Eq` on a `Hand` directly, but it's substantially more correct. Really, it's not even different from what you're proposing; the key insight is that a "suitably defined type" is the hand's rank, not the hand itself.
