### ISSUE TITLE
Bad naming convention in the nucleotide exercises

### ISSUE THREAD

**Issue by nickeb96** [exercism/rust#986]
Acronyms and Initialisms types should all be UpperCamelCase.  So `DNA` and `RNA` structs should be `Dna` and `Rna`.

Here's the proof: <https://rust-lang.github.io/rfcs/0430-finalizing-naming-conventions.html>

**Comment by kotp** [comment]
I don't see anything governing naming for "structs" in that document.

If the `DNA` and `RNA` are constant variables, or static variables, then
I would say it follows convention.  If they are types, traits or enum
variants, then perhaps all caps is still alright, given context of
reading.

I would say that there is a reason why it is called a "convention"
rather than "absolute law" as it gives room for doing sensible things
within the spirit of the convention.

**Comment by kotp** [comment]
That said, I encourage a pull request to give folks a chance to see exactly where and what would be changed.

**Comment by petertseng** [comment]
To clarify: structs are types. So the rules for types should be followed.

Even though the document only talks about acronyms and not initialisms, the fact that they use UUID as an example of an acronym makes clear that they meant to say "acronyms and initialisms" instead of "acronyms". UUID, DNA, and RNA are all initialisms and so we'll consider them to fall under the "acronyms [sic] count as one word".

So the suggestion in the issue body should be applied.

**Comment by nickeb96** [comment]
Yes, structs are types in Rust, so the document linked does apply here.  Btw structs are types (not constants or statics) in almost all languages that have them including C, C++, C#, D, Swift, and their derivatives.

These should really be changed to UpperCamelCase since it goes against the standard for no reason.  It specifically states how to handle acronyms/initialisms so going against it really isn't "within the spirit of the convention".  I was mentoring someone on one of the nucleotide exercises and thought this was their mistake at first.  The base templates people start with and learn from should really be correct.

It's not an inconsistently applied rule either.  Here are some examples from the standard library:

- UdpSocket
- TcpSocket
- IpAddr
- Rhs
- AsciiExt
- OsString


Here is the commit that changed it and would need to be undone or changed: 70ecf1c1e39dc900f57e0a288b90c89d4b49e0ac

I didn't check the other exercises involving nucleotides, but they may need to be changed too.

**Comment by kotp** [comment]
> The base templates people start with and learn from should really be correct.

Absolutely.

It is jarring to see UDP, TCP, ASCII, OS, and IP as not capitalized to indicate that they are initials, but then, yes the following "S", "S", "E", "S" and "A" become troublesome.  Though yes, if that is a rule (rather than a convention) then follow the rule, absolutely.  Until you are at the "master" level and know when you can break or bend those rules.  I have no idea what `Rhs` means, so would not even know how to comment on that.

For purpose of teaching, though, I agree present the more correct thing, and the student will decide when they become ingrained in the industry to make change these rules.

I would also say to use the word "structures" rather than "structs" if that is what they are... otherwise mark them as code, if they are indeed code.  Even Rust officially seems to prefer using the real words:

> Structures. There are three types of structures ("structs") that can be created using the struct keyword: Tuple structs, which are, basically, named tuples. -- [Structures](https://doc.rust-lang.org/stable/rust-by-example/custom_types/structs.html)

**Comment by kotp** [comment]
To clarify a little bit as well, the document does not show that these are directly used for structures, but needs that "gap" in knowledge that @peterseng provided in his initial response...

> To clarify: structs are types. So the rules for types should be followed.
